/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionale.ordini.biciclette;

import javax.swing.JOptionPane;

/**
 *
 * @author Utente
 */
public class InserisciGiacenza extends javax.swing.JFrame {

    /**
     * Creates new form InserisciGiacenza
     */
    Giacenza g;
    public InserisciGiacenza(Giacenza g) {
        initComponents();
        this.g = g;
        setVisible(true);
        JOptionPane.showMessageDialog(null, "cazzo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextCoroneL = new javax.swing.JTextField();
        jTextRaggi = new javax.swing.JTextField();
        jTextCoroneC = new javax.swing.JTextField();
        jTextCerchioniA = new javax.swing.JTextField();
        jTextCatene = new javax.swing.JTextField();
        jTextTelaioB = new javax.swing.JTextField();
        jTextCerchioniB = new javax.swing.JTextField();
        jTextTelaioA = new javax.swing.JTextField();
        jTextCerchioniC = new javax.swing.JTextField();
        jTextTelaioC = new javax.swing.JTextField();
        jTextVerniceGC = new javax.swing.JTextField();
        jTextVerniceB = new javax.swing.JTextField();
        jTextVerniceGialla = new javax.swing.JTextField();
        jTextVerniceGS = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextManubriA = new javax.swing.JTextField();
        jTextManubriC = new javax.swing.JTextField();
        jTextManubriB = new javax.swing.JTextField();
        jTextCambioD = new javax.swing.JTextField();
        jTextCambioU = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Inserisci la giacenza");

        jLabel2.setText("Corone lunghe");

        jLabel3.setText("Corone corte");

        jLabel4.setText("Catene");

        jLabel5.setText("CerchioniA");

        jLabel6.setText("Raggi");

        jLabel7.setText("CerchioniB");

        jLabel8.setText("CerchioniC");

        jLabel9.setText("TelaioA");

        jLabel10.setText("TelaioB");

        jLabel11.setText("TelaioC");

        jLabel12.setText("Vernice bianca");

        jLabel13.setText("Vernice grigio chiaro");

        jLabel14.setText("Vernice grigio scuro");

        jLabel15.setText("Vernice gialla");

        jTextCoroneL.setText(" ");

        jTextRaggi.setText(" ");

        jTextCoroneC.setText(" ");

        jTextCerchioniA.setText(" ");

        jTextCatene.setText(" ");

        jTextTelaioB.setText(" ");

        jTextCerchioniB.setText(" ");

        jTextTelaioA.setText(" ");

        jTextCerchioniC.setText(" ");

        jTextTelaioC.setText(" ");

        jTextVerniceGC.setText(" ");

        jTextVerniceB.setText(" ");

        jTextVerniceGialla.setText(" ");

        jTextVerniceGS.setText(" ");

        jButton1.setText("Inserisci giacenza");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextManubriA.setText(" ");

        jTextManubriC.setText(" ");

        jTextManubriB.setText(" ");

        jTextCambioD.setText(" ");

        jTextCambioU.setText(" ");

        jLabel16.setText("ManubriA");

        jLabel17.setText("ManubriB");

        jLabel18.setText("ManubriC");

        jLabel19.setText("Cambio uomo");

        jLabel20.setText("Cambio donna");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCambioU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(jTextManubriC, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextManubriB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextManubriA)
                            .addComponent(jTextCambioD)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextCoroneL, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(jTextCoroneC)
                            .addComponent(jTextCatene)
                            .addComponent(jTextRaggi)
                            .addComponent(jTextCerchioniA)
                            .addComponent(jTextCerchioniB)
                            .addComponent(jTextCerchioniC)
                            .addComponent(jTextTelaioA)
                            .addComponent(jTextTelaioB)
                            .addComponent(jTextTelaioC)
                            .addComponent(jTextVerniceB)
                            .addComponent(jTextVerniceGC)
                            .addComponent(jTextVerniceGS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextVerniceGialla)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextCoroneL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextCoroneC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextCatene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextRaggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextCerchioniA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextCerchioniB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextCerchioniC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextTelaioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextTelaioB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextTelaioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextVerniceB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextVerniceGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextVerniceGS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextVerniceGialla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextManubriA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextManubriB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextManubriC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextCambioU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextCambioD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jTextCambioD.getText() != null){
            g.setCambio_donna(Integer.parseInt(jTextCambioD.getText()));
            jTextCambioD.setText("");
        }
        if(jTextCambioU.getText() != null){
            g.setCambio_uomo(Integer.parseInt(jTextCambioU.getText()));
            jTextCambioD.setText("");
        }
        if(jTextCatene.getText() != null){
            g.setCatene(Integer.parseInt(jTextCambioD.getText()));
            jTextCambioD.setText("");
        }
        if(jTextCerchioniA.getText() != null){
            g.setCerchioni_a(Integer.parseInt(jTextCatene.getText()));
            jTextCambioD.setText("");
        }
        if(jTextCerchioniB.getText() != null){
            g.setCerchioni_b(Integer.parseInt(jTextCerchioniB.getText()));
            jTextCambioD.setText("");
        }
        if(jTextCerchioniC.getText() != null){
            g.setCerchioni_c(Integer.parseInt(jTextCerchioniC.getText()));
            jTextCambioD.setText("");
        }
        if(jTextCoroneC.getText() != null){
            g.setCorone_corte(Integer.parseInt(jTextCoroneC.getText()));
            jTextCambioD.setText("");
        }
        if(jTextCoroneL.getText() != null){
            g.setCorone_lunghe(Integer.parseInt(jTextCoroneL.getText()));
            jTextCambioD.setText("");
        }
        if(jTextManubriA.getText() != null){
            g.setManubri_a(Integer.parseInt(jTextManubriA.getText()));
            jTextCambioD.setText("");
        }
        if(jTextManubriB.getText() != null){
            g.setManubri_b(Integer.parseInt(jTextManubriB.getText()));
            jTextCambioD.setText("");
        }
        if(jTextManubriC.getText() != null){
            g.setManubri_c(Integer.parseInt(jTextManubriC.getText()));
            jTextCambioD.setText("");
        }
        if(jTextRaggi.getText() != null){
            g.setRaggi(Integer.parseInt(jTextRaggi.getText()));
            jTextCambioD.setText("");
        }
        if(jTextTelaioA.getText() != null){
            g.setTelai_a(Integer.parseInt(jTextTelaioA.getText()));
            jTextCambioD.setText("");
        }
        if(jTextTelaioB.getText() != null){
            g.setTelai_b(Integer.parseInt(jTextTelaioB.getText()));
            jTextCambioD.setText("");
        }
        if(jTextTelaioC.getText() != null){
            g.setTelai_c(Integer.parseInt(jTextTelaioC.getText()));
            jTextCambioD.setText("");
        }
        if(jTextVerniceB.getText() != null){
            g.setVernice_bianca(Integer.parseInt(jTextVerniceB.getText()));
            jTextCambioD.setText("");
        }
        if(jTextVerniceGC.getText() != null){
            g.setVernice_grigio_chiaro(Integer.parseInt(jTextVerniceGC.getText()));
            jTextCambioD.setText("");
        }
        if(jTextVerniceGS.getText() != null){
            g.setVernice_grigio_scuro(Integer.parseInt(jTextVerniceGS.getText()));
            jTextCambioD.setText("");
        }
        if(jTextVerniceGialla.getText() != null){
            g.setVernice_gialla(Integer.parseInt(jTextVerniceGialla.getText()));
            jTextCambioD.setText("");
        }
         
        JOptionPane.showMessageDialog(null,g.toString());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextCambioD;
    private javax.swing.JTextField jTextCambioU;
    private javax.swing.JTextField jTextCatene;
    private javax.swing.JTextField jTextCerchioniA;
    private javax.swing.JTextField jTextCerchioniB;
    private javax.swing.JTextField jTextCerchioniC;
    private javax.swing.JTextField jTextCoroneC;
    private javax.swing.JTextField jTextCoroneL;
    private javax.swing.JTextField jTextManubriA;
    private javax.swing.JTextField jTextManubriB;
    private javax.swing.JTextField jTextManubriC;
    private javax.swing.JTextField jTextRaggi;
    private javax.swing.JTextField jTextTelaioA;
    private javax.swing.JTextField jTextTelaioB;
    private javax.swing.JTextField jTextTelaioC;
    private javax.swing.JTextField jTextVerniceB;
    private javax.swing.JTextField jTextVerniceGC;
    private javax.swing.JTextField jTextVerniceGS;
    private javax.swing.JTextField jTextVerniceGialla;
    // End of variables declaration//GEN-END:variables
}


