/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionale.ordini.biciclette;

import javax.swing.JOptionPane;

/**
 *
 * @author Utente
 */
public class InserisciGiacenze extends javax.swing.JFrame {

    /**
     * Creates new form InserisciGiacenze
     */
    private Giacenza g;
    private app a;
    public InserisciGiacenze(app a){
        initComponents();
        setVisible(true);
        this.a = a;
        this.g = a.getGiacenza();
        inizializza();
    }

    private void inizializza() {

        jTextCambioD.setText(Integer.toString(g.getCambio_donna()));

        jTextCambioU.setText(Integer.toString(g.getCambio_uomo()));
            

        jTextCatene.setText(Integer.toString(g.getCatene()));
        

        jTextCerchioniA.setText(Integer.toString(g.getCerchioni_a()));
        

        jTextCerchioniB.setText(Integer.toString(g.getCerchioni_b()));
        

        jTextCerchioniC.setText(Integer.toString(g.getCerchioni_c()));
        

        jTextCoroneC.setText(Integer.toString(g.getCorone_corte()));
        

        jTextCoroneL.setText(Integer.toString(g.getCorone_lunghe()));
        

        jTextManubriA.setText(Integer.toString(g.getManubri_a()));
        

        jTextManubriB.setText(Integer.toString(g.getManubri_b()));
        
        jTextManubriC.setText(Integer.toString(g.getManubri_c()));
        

        jTextRaggi.setText(Integer.toString(g.getRaggi()));
        

        jTextTelaioA.setText(Integer.toString(g.getTelai_a()));
        

        jTextTelaioB.setText(Integer.toString(g.getTelai_b()));
        

        jTextTelaioC.setText(Integer.toString(g.getTelai_c()));
        

        jTextVerniceB.setText(Integer.toString(g.getVernice_bianca()));
        

        jTextVerniceGC.setText(Integer.toString(g.getVernice_grigio_chiaro()));
        

        jTextVerniceGS.setText(Integer.toString(g.getVernice_grigio_scuro()));
        
        
        jTextVerniceGialla.setText(Integer.toString(g.getVernice_gialla()));
        
        
        jTextRuotaA.setText(Integer.toString(g.getRuota_a()));
        
        
        jTextRuotaB.setText(Integer.toString(g.getRuota_b()));
        
        
        jTextRuotaC.setText(Integer.toString(g.getRuota_c()));
        
        
        jTextGommaA.setText(Integer.toString(g.getGomma_a()));
        
        
        jTextGommaB.setText(Integer.toString(g.getGomma_b()));
        
        
        jTextGommaC.setText(Integer.toString(g.getGomma_c()));
    }
    
    
    private void aggiorna_originale(){
        a.setGiacenza(g);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextTelaioC = new javax.swing.JTextField();
        jTextVerniceGC = new javax.swing.JTextField();
        jTextVerniceB = new javax.swing.JTextField();
        jTextVerniceGialla = new javax.swing.JTextField();
        jTextVerniceGS = new javax.swing.JTextField();
        Inserisci = new javax.swing.JButton();
        jTextCoroneL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextRaggi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextCoroneC = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextCerchioniA = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextCatene = new javax.swing.JTextField();
        jTextTelaioB = new javax.swing.JTextField();
        jTextCerchioniB = new javax.swing.JTextField();
        jTextTelaioA = new javax.swing.JTextField();
        jTextCerchioniC = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextGommaA = new javax.swing.JTextField();
        jTextGommaC = new javax.swing.JTextField();
        jTextCambioU = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextRuotaB = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextRuotaA = new javax.swing.JTextField();
        jTextManubriA = new javax.swing.JTextField();
        jTextRuotaC = new javax.swing.JTextField();
        jTextGommaB = new javax.swing.JTextField();
        jTextManubriC = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextManubriB = new javax.swing.JTextField();
        jTextCambioD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Inserisci.setText("Inserisci giacenza");
        Inserisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserisciActionPerformed(evt);
            }
        });

        jTextCoroneL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCoroneLActionPerformed(evt);
            }
        });

        jLabel8.setText("CerchioniC");

        jLabel9.setText("TelaioA");

        jLabel10.setText("TelaioB");

        jTextRaggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRaggiActionPerformed(evt);
            }
        });

        jLabel11.setText("TelaioC");

        jLabel12.setText("Vernice bianca");

        jLabel13.setText("Vernice grigio chiaro");

        jLabel14.setText("Vernice grigio scuro");

        jLabel15.setText("Vernice gialla");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Inserisci la giacenza");

        jLabel2.setText("Corone lunghe");

        jLabel3.setText("Corone corte");

        jLabel4.setText("Catene");

        jLabel5.setText("CerchioniA");

        jLabel6.setText("Raggi");

        jLabel7.setText("CerchioniB");

        jLabel27.setText("GommaB");

        jLabel28.setText("GommaC");

        jTextGommaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGommaCActionPerformed(evt);
            }
        });

        jLabel29.setText("ManubriA");

        jLabel30.setText("ManubriB");

        jLabel31.setText("ManubriC");

        jLabel32.setText("Cambio uomo");

        jLabel33.setText("Cambio donna");

        jLabel34.setText("RuotaA");

        jLabel35.setText("RuotaB");

        jLabel36.setText("RuotaC");

        jTextRuotaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRuotaCActionPerformed(evt);
            }
        });

        jLabel37.setText("GommaA");

        jTextCambioD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCambioDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inserisci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextVerniceGS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextVerniceGC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextVerniceB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTelaioC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTelaioB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTelaioA, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCerchioniC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCerchioniB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCerchioniA, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCoroneC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCoroneL, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextRaggi)
                            .addComponent(jTextVerniceGialla))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextManubriB, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jTextManubriC, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextCambioU, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextCambioD, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextManubriA)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel36))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextRuotaB, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jTextRuotaA)
                                    .addComponent(jTextRuotaC)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(59, 59, 59)
                                .addComponent(jTextGommaC, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel4))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextGommaA)
                                    .addComponent(jTextGommaB)
                                    .addComponent(jTextCatene)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jTextManubriA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jTextManubriB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextCoroneL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextCoroneC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(jTextManubriC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jTextCambioU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jTextCambioD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(jTextRuotaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(jTextRuotaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(jTextRuotaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(jTextGommaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jTextGommaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jTextGommaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextCatene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextRaggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextCerchioniA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextCerchioniB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextCerchioniC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextTelaioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextTelaioB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextTelaioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextVerniceB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextVerniceGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextVerniceGS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextVerniceGialla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(Inserisci)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InserisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserisciActionPerformed
        if(!jTextCambioD.getText().equals("")){
            g.setCambio_donna(Integer.parseInt(jTextCambioD.getText()));
        }
        jTextCambioD.setText(Integer.toString(g.getCambio_donna()));

        if(!jTextCambioU.getText().equals("")){
            g.setCambio_uomo(Integer.parseInt(jTextCambioU.getText()));
        }
        jTextCambioU.setText(Integer.toString(g.getCambio_uomo()));
            
        if(!jTextCatene.getText().equals("")){
            g.setCatene(Integer.parseInt(jTextCatene.getText()));
        }
        jTextCatene.setText(Integer.toString(g.getCatene()));
        
        if(!jTextCerchioniA.getText().equals("")){
            g.setCerchioni_a(Integer.parseInt(jTextCerchioniA.getText()));
        }
        jTextCerchioniA.setText(Integer.toString(g.getCerchioni_a()));
        
        if(!jTextCerchioniB.getText().equals("")){
            g.setCerchioni_b(Integer.parseInt(jTextCerchioniB.getText()));
        }
        jTextCerchioniB.setText(Integer.toString(g.getCerchioni_b()));
        
        if(!jTextCerchioniC.getText().equals("")){
            g.setCerchioni_c(Integer.parseInt(jTextCerchioniC.getText()));
        }
        jTextCerchioniC.setText(Integer.toString(g.getCerchioni_c()));
        
        if(!jTextCoroneC.getText().equals("")){
            g.setCorone_corte(Integer.parseInt(jTextCoroneC.getText()));
        }
        jTextCoroneC.setText(Integer.toString(g.getCorone_corte()));
        
        if(!jTextCoroneL.getText().equals("")){
            g.setCorone_lunghe(Integer.parseInt(jTextCoroneL.getText()));
        }
        jTextCoroneL.setText(Integer.toString(g.getCorone_lunghe()));
        
        if(!jTextManubriA.getText().equals("")){
            g.setManubri_a(Integer.parseInt(jTextManubriA.getText()));
        }
        jTextManubriA.setText(Integer.toString(g.getManubri_a()));
        
        if(!jTextManubriB.getText().equals("")){
            g.setManubri_b(Integer.parseInt(jTextManubriB.getText()));
        }
        jTextManubriB.setText(Integer.toString(g.getManubri_b()));
        
        if(!jTextManubriC.getText().equals("")){
            g.setManubri_c(Integer.parseInt(jTextManubriC.getText()));
        }
        jTextManubriC.setText(Integer.toString(g.getManubri_c()));
        
        if(!jTextRaggi.getText().equals("")){
            g.setRaggi(Integer.parseInt(jTextRaggi.getText()));
        }
        jTextRaggi.setText(Integer.toString(g.getRaggi()));
        
        if(!jTextTelaioA.getText().equals("")){
            g.setTelai_a(Integer.parseInt(jTextTelaioA.getText()));
        }
        jTextTelaioA.setText(Integer.toString(g.getTelai_a()));
        
        if(!jTextTelaioB.getText().equals("")){
            g.setTelai_b(Integer.parseInt(jTextTelaioB.getText()));
        }
        jTextTelaioB.setText(Integer.toString(g.getTelai_b()));
        
        if(!jTextTelaioC.getText().equals("")){
            g.setTelai_c(Integer.parseInt(jTextTelaioC.getText()));
        }
        jTextTelaioC.setText(Integer.toString(g.getTelai_c()));
        
        if(!jTextVerniceB.getText().equals("")){
            g.setVernice_bianca(Integer.parseInt(jTextVerniceB.getText()));
        }
        jTextVerniceB.setText(Integer.toString(g.getVernice_bianca()));
        
        if(!jTextVerniceGC.getText().equals("")){
            g.setVernice_grigio_chiaro(Integer.parseInt(jTextVerniceGC.getText()));
        }
        jTextVerniceGC.setText(Integer.toString(g.getVernice_grigio_chiaro()));
        
        if(!jTextVerniceGS.getText().equals("")){
            g.setVernice_grigio_scuro(Integer.parseInt(jTextVerniceGS.getText()));
        }
        jTextVerniceGS.setText(Integer.toString(g.getVernice_grigio_scuro()));
        
        if(!jTextVerniceGialla.getText().equals("")){
            g.setVernice_gialla(Integer.parseInt(jTextVerniceGialla.getText()));
        }
        jTextVerniceGialla.setText(Integer.toString(g.getVernice_gialla()));
        
        if(!jTextRuotaA.getText().equals("")){
            g.setRuota_a(Integer.parseInt(jTextRuotaA.getText()));
        }
        jTextRuotaA.setText(Integer.toString(g.getRuota_a()));
        
        if(!jTextRuotaB.getText().equals("")){
            g.setRuota_b(Integer.parseInt(jTextRuotaB.getText()));
        }
        jTextRuotaB.setText(Integer.toString(g.getRuota_b()));
        
        if(!jTextRuotaC.getText().equals("")){
            g.setRuota_c(Integer.parseInt(jTextRuotaC.getText()));
        }
        jTextRuotaC.setText(Integer.toString(g.getRuota_c()));
        
        if(!jTextGommaA.getText().equals("")){
            g.setGomma_a(Integer.parseInt(jTextGommaA.getText()));
        }
        jTextGommaA.setText(Integer.toString(g.getGomma_a()));
        
        if(!jTextGommaA.getText().equals("")){
            g.setGomma_b(Integer.parseInt(jTextGommaA.getText()));
        }
        jTextGommaA.setText(Integer.toString(g.getGomma_b()));
        
        if(!jTextGommaA.getText().equals("")){
            g.setGomma_c(Integer.parseInt(jTextGommaA.getText()));
        }
        jTextGommaA.setText(Integer.toString(g.getGomma_c()));
        
        aggiorna_originale();
        this.dispose();
    }//GEN-LAST:event_InserisciActionPerformed

    private void jTextCoroneLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCoroneLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCoroneLActionPerformed

    private void jTextRaggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRaggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRaggiActionPerformed

    private void jTextGommaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGommaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGommaCActionPerformed

    private void jTextRuotaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRuotaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRuotaCActionPerformed

    private void jTextCambioDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCambioDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCambioDActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inserisci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextCambioD;
    private javax.swing.JTextField jTextCambioU;
    private javax.swing.JTextField jTextCatene;
    private javax.swing.JTextField jTextCerchioniA;
    private javax.swing.JTextField jTextCerchioniB;
    private javax.swing.JTextField jTextCerchioniC;
    private javax.swing.JTextField jTextCoroneC;
    private javax.swing.JTextField jTextCoroneL;
    private javax.swing.JTextField jTextGommaA;
    private javax.swing.JTextField jTextGommaB;
    private javax.swing.JTextField jTextGommaC;
    private javax.swing.JTextField jTextManubriA;
    private javax.swing.JTextField jTextManubriB;
    private javax.swing.JTextField jTextManubriC;
    private javax.swing.JTextField jTextRaggi;
    private javax.swing.JTextField jTextRuotaA;
    private javax.swing.JTextField jTextRuotaB;
    private javax.swing.JTextField jTextRuotaC;
    private javax.swing.JTextField jTextTelaioA;
    private javax.swing.JTextField jTextTelaioB;
    private javax.swing.JTextField jTextTelaioC;
    private javax.swing.JTextField jTextVerniceB;
    private javax.swing.JTextField jTextVerniceGC;
    private javax.swing.JTextField jTextVerniceGS;
    private javax.swing.JTextField jTextVerniceGialla;
    // End of variables declaration//GEN-END:variables
}
